export const image = {
  logo: require('../images/logo.png'),
  faceID: require('../images/FaceID.png'),
  logoAuthen: require('../images/img_authen.png'),
  eye: require('../images/eye.png'),
  savePass: require('../images/savePass.png'),
  errorAuth: require('../images/errorAuth.png'),
  find: require('../images/find.png'),
  filter: require('../images/filter.png'),
  noti: require('../images/noti.png'),
  setting: require('../images/setting.png'),
  hotline: require('../images/hotline.png'),
  history: require('../images/history.png'),
  powerMeter: require('../images/power.png'),
  seeMore: require('../images/seeMore.png'),
  back: require('../images/back.png'),
  chooseFile: require('../images/chooseFile.png'),
  draw: require('../images/draw.png'),
};
